name: Keep Backend Warm

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend health endpoint
        run: curl -s https://refer-and-earn-rc14.onrender.com/health > /dev/null
